### ISSUE TITLE
video size

### ISSUE THREAD

**Issue by olalekan-opadere** [mahirozdin/Twitter-Video-Downloader#1]
How can i get the video size for each of the video options available rather than only the bitrate?

**Comment by Philipinho** [comment]
You can do so by sending a head request to the video URL.
```
function get_file_size($video_url){
  $head = array_change_key_case(get_headers($video_url, TRUE));
  $file_size = isset($head['content-length']) ? $head['content-length'] : 0;
  return $file_size;
}
```

You can then format the returned file size to a human-readable form.

**Comment by olalekan-opadere** [comment]
Thank you
